name: Branch Protection Audit

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to audit'
        required: true
        default: 'main'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install requests
      run: pip install requests

    - name: Run audit script
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        ORG_NAME: test-for-my-prg     # orgの名前に変える
        BRANCH: ${{ github.event.inputs.branch }}
      run: python audit_branch_protection.py

    - name: Upload CSV artifact
      uses: actions/upload-artifact@v4
      with:
        name: protection_audit
        path: |
          クラシック保護マトリックス.csv
          ルールセット個別詳細.csv

